#!/usr/bin/env node
// scripts/gen-index.js
//
// Regenerates the language <optgroup> block and the CodeMirror mode <script>
// tags in src-tauri/dist/index.html from the single LANGUAGES / MODE_SCRIPTS
// table in src-tauri/dist/logic.js. Run after editing that table:
//
//     node scripts/gen-index.js
//
// It only rewrites the regions between the AUTO-GENERATED markers, so any
// hand-written HTML around them is preserved. Also fails loudly if a referenced
// mode file is missing, keeping the app fully offline and self-consistent.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const DIST = path.join(ROOT, 'src-tauri', 'dist');
const INDEX = path.join(DIST, 'index.html');
const L = require(path.join(DIST, 'logic.js'));

function fail(msg) {
    console.error('gen-index: ' + msg);
    process.exit(1);
}

// --- Sanity checks -------------------------------------------------------
for (const rel of L.MODE_SCRIPTS) {
    if (!fs.existsSync(path.join(DIST, rel))) fail(`missing vendored script: ${rel}`);
}
for (const v of new Set(Object.values(L.EXT_MODE))) {
    if (!L.LANG_LABELS[v]) fail(`extension maps to "${v}" which has no label`);
}

function esc(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// --- Build the <select> options, grouped, preserving table order ---------
const groups = [];
const byGroup = new Map();
for (const lang of L.LANGUAGES) {
    if (!byGroup.has(lang.group)) { byGroup.set(lang.group, []); groups.push(lang.group); }
    byGroup.get(lang.group).push(lang);
}

const optLines = [];
for (const group of groups) {
    const langs = byGroup.get(group);
    // The lone "General" entry (Plain Text) reads better without a heading.
    if (group === 'General') {
        for (const l of langs) optLines.push(`            <option value="${esc(l.value)}">${esc(l.label)}</option>`);
        continue;
    }
    optLines.push(`            <optgroup label="${esc(group)}">`);
    for (const l of langs) optLines.push(`                <option value="${esc(l.value)}">${esc(l.label)}</option>`);
    optLines.push('            </optgroup>');
}
const optBlock = optLines.join('\n');

// --- Build the mode <script> tags ----------------------------------------
const scriptBlock = L.MODE_SCRIPTS
    .map(src => `    <script src="${src}"></script>`)
    .join('\n');

// --- Inject between markers ----------------------------------------------
function replaceRegion(html, name, body) {
    const start = `<!-- ${name}:START (generated by scripts/gen-index.js — do not edit by hand) -->`;
    const end = `<!-- ${name}:END -->`;
    const re = new RegExp(
        escapeRe(start) + '[\\s\\S]*?' + escapeRe(end)
    );
    if (!re.test(html)) fail(`could not find ${name} markers in index.html`);
    return html.replace(re, `${start}\n${body}\n${end}`);
}
function escapeRe(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

let html = fs.readFileSync(INDEX, 'utf8');
html = replaceRegion(html, 'MODE-SCRIPTS', scriptBlock);
html = replaceRegion(html, 'LANG-OPTIONS', optBlock);
fs.writeFileSync(INDEX, html);

console.log(`gen-index: wrote ${L.LANGUAGES.length} languages, ${L.MODE_SCRIPTS.length} scripts to index.html`);
