#!/usr/bin/env bash
# Dependency-license audit for the source-built distro packages (issue #17).
#
# Source-built distros (Debian #7, Fedora/RHEL #8, openSUSE #12, Gentoo #13)
# must account for every dependency's licence before they will ship the crate
# tree. This script is the reusable groundwork #17 calls for: it reads the
# resolved dependency graph straight from `cargo metadata` (no network, no crate
# downloads) and emits a canonical licence inventory that those packagers audit
# against — and that a Debian dependency-gap report (#7) consumes as its input.
#
# The whole native tree is pure-Rust and permissively licensed; the point of the
# gate is to *keep* it that way. Every crate's SPDX expression is classified
# against an allowlist of licences that are all GPL-3.0-or-later-compatible AND
# accepted by Debian (DFSG) / Fedora. A crate passes if at least one of its
# licence choices is fully allowed — so a dual `X OR GPL-2.0-only` crate passes
# on its permissive branch (we pick that branch), while a copyleft-*only* crate
# fails and blocks the audit until a human decides.
#
# The vendored code + font (the iced `text_editor` fork, DejaVu Sans Mono) are
# NOT crate dependencies and are recorded separately in ../THIRD-PARTY.md (#77);
# this audit covers only the `Cargo.lock` crate graph, which THIRD-PARTY.md
# deliberately does not enumerate.
#
# Usage:
#   scripts/license-audit.sh              # print the inventory + summary to stdout
#   scripts/license-audit.sh --write      # (re)generate packaging/CRATE-LICENSES.md
#   scripts/license-audit.sh --check      # CI gate: fail if that file is stale
#
# In every mode the script exits non-zero if any crate needs manual review, so it
# doubles as a "did someone just add a copyleft-only dependency?" gate.
#
# Platform: the graph is filtered to one target triple (default: the host's) so
# the audit reflects what the Linux source distros actually build — Windows- and
# macOS-only crates (windows-sys, core-foundation, …) are correctly excluded.
# Override with TARGET=<triple>.
#
# Metadata resolves offline (local checkout / registry cache) by default; set
# LICENSE_AUDIT_ONLINE=1 to let cargo populate the index first — needed in CI,
# where the registry is not pre-cached.
#
# Requires: cargo, jq.
set -euo pipefail

cd "$(dirname "$0")/.."

# Pin collation so the generated ordering is identical on every machine — glibc's
# locale-aware sort ignores punctuation (tiny-xlib after tinyvec_macros) while a C
# locale sorts by byte (tiny-xlib before tinystr); without this the CI --check
# re-render disagrees with a locally generated file.
export LC_ALL=C

TARGET="${TARGET:-$(rustc -vV | sed -n 's/^host: //p')}"
OUT="packaging/CRATE-LICENSES.md"

# Licences that are all GPL-3.0-or-later-compatible and accepted by Debian +
# Fedora. Extend this list only after confirming a new licence clears both.
ALLOWED='{
  "MIT":1,"Apache-2.0":1,"Apache-2.0 WITH LLVM-exception":1,
  "BSD-2-Clause":1,"BSD-3-Clause":1,"ISC":1,
  "Zlib":1,"0BSD":1,"Unlicense":1,"Unicode-3.0":1
}'

command -v jq >/dev/null || { echo "error: jq is required" >&2; exit 2; }

offline_flag=(--offline)
[ -n "${LICENSE_AUDIT_ONLINE:-}" ] && offline_flag=()
meta="$(cargo metadata --format-version 1 "${offline_flag[@]}" --filter-platform "$TARGET")"

# One jq program shared by the report and the gate. Emits, per external crate,
# a TSV line: status<TAB>name<TAB>version<TAB>license  (status = OK | REVIEW).
JQ='
  def allowed: '"$ALLOWED"';
  # an OR-group passes if every AND-ed token in it is allowed
  def group_ok($g): ($g | split(" AND ") | map(gsub("^ +| +$";""))
                       | all(. as $t | allowed[$t] != null));
  def classify($lic):
    (($lic // "") | gsub("[()]";" ") | gsub("  +";" ") | gsub("^ +| +$";"")
       | [splits(" OR |/")] | map(gsub("^ +| +$";""))) as $groups
    | if ($groups | any(group_ok(.))) then "OK" else "REVIEW" end;
  (.workspace_members) as $ws
  | .packages[]
  | select(.id as $id | ($ws | index($id)) | not)
  | [classify(.license), .name, (.version), (.license // "NONE")]
  | @tsv
'

rows="$(jq -r "$JQ" <<<"$meta" | sort -t$'\t' -k2,2)"

review="$(awk -F'\t' '$1=="REVIEW"' <<<"$rows" || true)"
total="$(wc -l <<<"$rows" | tr -d ' ')"

# Build the Markdown report to stdout.
render() {
  cat <<EOF
<!-- GENERATED by scripts/license-audit.sh — do not edit by hand. -->
# Crate licence inventory

Canonical licence record of Notepad Extra's **crate dependencies**, for the
source-built distro packages (Debian #7, Fedora/RHEL #8, openSUSE #12,
Gentoo #13) and the umbrella dependency strategy (#17). Regenerate with
\`scripts/license-audit.sh --write\`.

- **Resolved for target:** \`$TARGET\` (the Linux source distros' build target;
  Windows/macOS-only crates are excluded).
- **External crates:** $total (the three workspace crates are ours, GPL-3.0-or-later).
- **Vendored code + font** (iced \`text_editor\` fork, DejaVu Sans Mono) are not
  crates — see [THIRD-PARTY.md](../THIRD-PARTY.md) (#77).
- **Per-distro dependency lists** (Gentoo \`CRATES=\`, RPM bundled \`Provides:\`)
  live in [deps/](deps/), generated by \`scripts/packaging-deps.sh\`.

Every crate below is licensed under a permissive, GPL-3.0-or-later-compatible
licence that Debian (DFSG) and Fedora both accept. Dual \`… OR …\` crates are
shipped under their permissive branch.

## Summary by licence

| SPDX expression | Crates |
| --- | ---: |
EOF
  awk -F'\t' '{c[$4]++} END{for(k in c) printf "| %s | %d |\n", k, c[k]}' <<<"$rows" \
    | sort -t'|' -k3 -rn
  cat <<EOF

## Inventory

| Crate | Version | SPDX licence |
| --- | --- | --- |
EOF
  awk -F'\t' '{printf "| %s | %s | %s |\n", $2, $3, $4}' <<<"$rows"
}

case "${1:-}" in
  --write)
    render > "$OUT"
    echo "wrote $OUT ($total crates)"
    ;;
  --check)
    if ! diff -u "$OUT" <(render) ; then
      echo "error: $OUT is stale — run scripts/license-audit.sh --write" >&2
      exit 1
    fi
    echo "$OUT is up to date ($total crates)"
    ;;
  ""|--print)
    render
    ;;
  *)
    echo "usage: $0 [--print | --write | --check]" >&2
    exit 2
    ;;
esac

# The audit gate: any crate we could not clear automatically blocks the build.
if [ -n "$review" ]; then
  echo >&2
  echo "error: $(wc -l <<<"$review" | tr -d ' ') crate(s) need a manual licence review:" >&2
  awk -F'\t' '{printf "  %s %s — %s\n", $2, $3, $4}' <<<"$review" >&2
  exit 1
fi
