#!/usr/bin/env bash
# Per-distro dependency artifacts for the source-built packages (issue #17).
#
# The source-built distros each want the crate graph expressed in their own
# format. Three of those artifacts are pure functions of `Cargo.lock` and are
# generated here — offline, deterministically — so #8 / #12 / #13 each start
# with their dependency list already in hand:
#
#   gentoo   -> packaging/deps/gentoo-crates.txt      (cargo.eclass CRATES= list)
#   rpm      -> packaging/deps/rpm-bundled-provides.txt (Fedora/openSUSE
#               `Provides: bundled(crate(name)) = version`)
#
# Two more artifacts need the network (crate sources / the Debian archive), so
# they are runnable helpers a packager invokes rather than committed data:
#
#   vendor      -> a `cargo vendor` tree + the `.cargo/config.toml` snippet the
#                  SRPM/ebuild builds against (Fedora/openSUSE/Gentoo).
#   debian-gap  -> for #7: which crates already exist in Debian as `rust-*`
#                  source packages vs. which the Debian Rust team must still
#                  package (vendoring is discouraged on Debian).
#
# Licences are handled by the sibling gate, scripts/license-audit.sh, and the
# vendored code/font by ../THIRD-PARTY.md (#77) — not repeated here.
#
# Usage:
#   scripts/packaging-deps.sh [all]        # (re)generate both offline lists
#   scripts/packaging-deps.sh gentoo|rpm   # just one
#   scripts/packaging-deps.sh --check      # CI gate: fail if either is stale
#   scripts/packaging-deps.sh vendor [DIR] # NETWORK: build the vendor tree
#   scripts/packaging-deps.sh debian-gap   # NETWORK: Debian availability report
#
# Platform: the offline lists resolve for one Linux target (default: the host's,
# override with TARGET=) — the same scope as the licence audit, and what these
# distros build. A packager who vendors *all* platforms (plain `cargo vendor`
# does) should regenerate the RPM list from the vendor tree; see `vendor` below.
#
# Metadata resolves offline by default; set PACKAGING_DEPS_ONLINE=1 (as CI does)
# to let cargo populate the registry index first.
#
# Requires: cargo, jq (+ curl for debian-gap).
set -euo pipefail

cd "$(dirname "$0")/.."

# Pin collation so the generated ordering is identical on every machine (glibc's
# locale-aware sort ignores punctuation, a C locale sorts by byte); otherwise the
# CI --check re-render disagrees with a locally generated file.
export LC_ALL=C

TARGET="${TARGET:-$(rustc -vV | sed -n 's/^host: //p')}"
DEPS_DIR="packaging/deps"
GENTOO_OUT="$DEPS_DIR/gentoo-crates.txt"
RPM_OUT="$DEPS_DIR/rpm-bundled-provides.txt"

command -v jq >/dev/null || { echo "error: jq is required" >&2; exit 2; }

# All external crates.io packages as sorted "name<TAB>version", offline.
crate_rows() {
  local offline=(--offline)
  [ -n "${PACKAGING_DEPS_ONLINE:-}" ] && offline=()
  cargo metadata --format-version 1 "${offline[@]}" --filter-platform "$TARGET" \
    | jq -r '
        (.workspace_members) as $ws
        | .packages[]
        | select(.id as $id | ($ws | index($id)) | not)
        | select((.source // "") | test("registry.*crates.io"))
        | "\(.name)\t\(.version)"' \
    | sort -u
}

gen_header() {  # $1 = human description
  printf '# GENERATED by scripts/packaging-deps.sh — do not edit by hand.\n'
  printf '# %s\n' "$1"
  printf '# Resolved for target %s; regenerate after any Cargo.lock change.\n' "$TARGET"
}

render_gentoo() {
  gen_header "Gentoo cargo.eclass CRATES list (#13). Paste into CRATES=\" ... \"."
  crate_rows | awk -F'\t' '{printf "%s@%s\n", $1, $2}'
}

render_rpm() {
  gen_header "Fedora/openSUSE bundled-crate Provides (#8/#12) for the .spec %files-adjacent block."
  crate_rows | awk -F'\t' '{printf "Provides: bundled(crate(%s)) = %s\n", $1, $2}'
}

do_vendor() {
  local dir="${1:-$DEPS_DIR/vendor}"
  echo "NETWORK: vendoring crate sources into $dir …" >&2
  cargo vendor "$dir" > "$DEPS_DIR/cargo-config-vendor.toml"
  echo >&2
  echo "Done. $dir holds every crate's source; the SRPM/ebuild builds against it" >&2
  echo "using $DEPS_DIR/cargo-config-vendor.toml (added under .cargo/config.toml)." >&2
  echo "The tree itself is gitignored — it is a build input, not committed data." >&2
  echo "Run scripts/license-audit.sh over the same graph for the licence manifest." >&2
}

do_debian_gap() {
  command -v curl >/dev/null || { echo "error: curl is required for debian-gap" >&2; exit 2; }
  echo "NETWORK: checking each crate against Debian (sources.debian.org) …" >&2
  echo "# Debian dependency-gap report (#7) — generated $(date -u +%Y-%m-%dT%H:%MZ)"
  echo "# Debian packages a crate as source package 'rust-<crate>' (binary"
  echo "# 'librust-<crate>-dev'); vendoring is discouraged, so every MISSING crate"
  echo "# below must be packaged via debcargo / the Debian Rust team before #7."
  local present=0 missing=0
  while IFS=$'\t' read -r name version; do
    # Debian source names lowercase the crate and map '_' -> '-'.
    local deb; deb="rust-$(printf '%s' "$name" | tr 'A-Z_' 'a-z-')"
    if curl -fsS "https://sources.debian.org/api/src/$deb/" >/dev/null 2>&1; then
      printf 'PRESENT  %s %s (%s)\n' "$name" "$version" "$deb"; present=$((present+1))
    else
      printf 'MISSING  %s %s (%s)\n' "$name" "$version" "$deb"; missing=$((missing+1))
    fi
  done < <(crate_rows)
  echo "# Summary: $present present, $missing to package." >&2
}

check_one() {  # $1 = file, $2 = renderer fn
  if ! diff -u "$1" <("$2"); then
    echo "error: $1 is stale — run scripts/packaging-deps.sh" >&2
    return 1
  fi
}

mkdir -p "$DEPS_DIR"
case "${1:-all}" in
  all)    render_gentoo > "$GENTOO_OUT"; render_rpm > "$RPM_OUT"
          echo "wrote $GENTOO_OUT and $RPM_OUT" ;;
  gentoo) render_gentoo > "$GENTOO_OUT"; echo "wrote $GENTOO_OUT" ;;
  rpm)    render_rpm > "$RPM_OUT";        echo "wrote $RPM_OUT" ;;
  --check)
          rc=0
          check_one "$GENTOO_OUT" render_gentoo || rc=1
          check_one "$RPM_OUT"    render_rpm    || rc=1
          [ $rc -eq 0 ] && echo "packaging dependency lists are up to date"
          exit $rc ;;
  vendor)      do_vendor "${2:-}" ;;
  debian-gap)  do_debian_gap ;;
  *) echo "usage: $0 [all|gentoo|rpm|--check|vendor [DIR]|debian-gap]" >&2; exit 2 ;;
esac
