name: "publish"

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-15-intel" # New label for Intel-based Macs
            args: "--target x86_64-apple-darwin"
          - platform: "macos-latest"    # Currently macOS 15 Arm64 (M1/M2/M3)
            args: "--target aarch64-apple-darwin"
          - platform: "windows-latest"
            args: ""
          - platform: "ubuntu-22.04"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-15-intel' && 'x86_64-apple-darwin' || matrix.platform == 'macos-latest' && 'aarch64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libfuse2

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "Notepad Extra v__VERSION__"
          releaseBody: "See the assets below to download."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
